match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
struct_lit_multiline_style = "ForceMulti"
normalize_comments = true
force_format_strings = true
format_strings = true
condense_wildcard_suffixes = true
