language: rust

rust:
  - stable
  - beta
  - nightly

  # For clippy.
  - nightly-2017-12-01

env:
  global:
    - CLIPPY_VERSION=0.0.175

before_script:
  - ./travis-script before_script

script:
  - ./travis-script script

os:
  - linux
  - osx
